# Generated by Django 3.0.8 on 2020-07-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_calculation', '0002_usercalculation_user_income_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercalculation',
            old_name='amount_left',
            new_name='amount',
        ),
    ]
